spring:
  profiles:
    active: dev

#第一份配置
---
server:
  port: 8001
mybatis:
  type-aliases-package: com.cqh.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
spring:
  profiles: dev #配置环境
  application:
    name: springcloud-config-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db02?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
#配置Eureka
eureka:
  client:
    service-url:   #向集群注册
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/
  instance:
    instance-id: provider-dept-01
#info配置
info:
  app.name: cqh-springcloud
  company.name: blog.cqh.com

#第二份配置
---
server:
  port: 8001
mybatis:
  type-aliases-package: com.cqh.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
spring:
  profiles: test #配置环境
  application:
    name: springcloud-config-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db03?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
#配置Eureka
eureka:
  client:
    service-url:   #向集群注册
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/
  instance:
    instance-id: provider-dept-01
#info配置
info:
  app.name: cqh-springcloud
  company.name: blog.cqh.com
